AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:


  RacketFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: example.function
      Runtime: provided
  Metadata:
    BuildMethod: makefile
