#!/bin/sh

set -euo pipefail

# shellcheck disable=SC2164
cd "$LAMBDA_TASK_ROOT"
MODULE=$(echo "$_HANDLER" | cut -d "." -f 1)
FUNCTION=$(echo "$_HANDLER" | cut -d "." -f 2)
EVENT=$(curl -D - -s "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
while [ "$EVENT" != "" ]; do
  ./distribute/bin/wrapper -m "$MODULE.rkt" -f "$FUNCTION" -e "$EVENT"
  EVENT=$(curl -D - -s "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
done
